base_url = "https://shikharish.github.io"
title = "Shikhar Soni"
build_search_index = false
generate_feeds = true
minify_html = true

[extra]
description = "The personal website of Shikhar Soni."

menu = [
    { name = "About", url = "@/about.md", weight = 1 },
    { name = "Now", url = "@/now.md", weight = 2 },
    { name = "Blog", url = "@/blog/_index.md", weight = 3 },
    { name = "Gallery", url = "@/gallery/_index.md", weight = 4 },
]

socials = [
    { name = "email", url = "mailto:shikharish05@gmail.com" },
    { name = "github", url = "https://github.com/shikharish/" },
    { name = "instagram", url = "https://instagram.com/shikharish.raw" },
    { name = "twitter", url = "https://twitter.com/shikharish" },
]
