base_url = "https://shikharish.github.io"
title = "Shikhar Soni"
build_search_index = false
generate_feeds = true
minify_html = true

[extra]
description = "The personal website of Shikhar Soni."
email = "shikharsoni05@gmail.com"
linkedin = "https://www.linkedin.com/in/shikharish/"

menu = [
    { name = "about", url = "@/about.md", weight = 1 },
    { name = "now", url = "@/now.md", weight = 2 },
    { name = "blog", url = "@/blog/_index.md", weight = 3 },
]

socials = [
    { name = "email", url = "mailto:shikharsoni05@gmail.com" },
    { name = "github", url = "https://github.com/shikharish/" },
    { name = "instagram", url = "https://instagram.com/shikharish.raw" },
    { name = "twitter", url = "https://twitter.com/shikharish" },
]
