base_url = "https://shikharish.github.io"
title = "Shikhar Soni"
build_search_index = false
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme="dark"
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name= "/About", url= "/about", weight= 1 },
    { name = "/Blog", url= "/blog", weight= 1 },
    { name = "/Gallery", url= "/gallery", weight= 1 },
]

socials = [
    { name= "github", url= "https://github.com/shikharish/", icon = "github" },
    { name= "instagram", url= "https://instagram.com/shikharish__", icon= "instagram" },
    { name= "twitter", url= "https://twitter.com/shikharish", icon= "twitter" },
]